apiVersion: v1
kind: Namespace
metadata:
  name: go-app-namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: go-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - go-server
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - go-server
                topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: go-server-container
        image: go-app-image:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"  
          limits:
            memory: "128Mi"
            cpu: "1000m" 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /start
            port: 8080
          failureThreshold: 30
          periodSeconds: 10 

apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-app-scale-up-cron-job
  namespace: go-app-namespace
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale-up-container
            image: bitnami/kubectl:latest
            command:
              - /bin/bash
              - -c
              - kubectl scale --replicas=4 deployment/go-server-deployment --namespace go-app-namespace
          restartPolicy: OnFailure

apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-app-scale-down-cron-job
  namespace: go-app-namespace
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale-down-container
            image: bitnami/kubectl:latest
            command:
              - /bin/bash
              - -c
              - kubectl scale --replicas=2 deployment/go-server-deployment --namespace go-app-namespace
          restartPolicy: OnFailure
